from typing import Protocol

from domain.sample import Sample, SampleId
from domain.user import UserId

from .models import NewSample


class SampleRepository(Protocol):
    async def create(self, sample: NewSample) -> Sample: ...
    async def get(self, sample_id: SampleId) -> Sample | None: ...
    async def delete(self, sample_id: SampleId) -> None: ...
    async def list(self, user_id: UserId, limit: int, offset: int) -> list[Sample]: ...
