from typing import Protocol

from domain.speech import Speech, SpeechId
from domain.user import UserId

from .models import NewSpeech


class SpeechRepository(Protocol):
    async def create(self, sample: NewSpeech) -> Speech: ...
    async def get(self, sample_id: SpeechId) -> Speech | None: ...
    async def delete(self, sample_id: SpeechId) -> None: ...
    async def list(self, user_id: UserId, limit: int, offset: int) -> list[Speech]: ...
