from typing import Protocol

from domain.user import Email, User, UserId

from .models import NewUser, UpdateUser


class UserRepository(Protocol):
    async def create(self, user: NewUser) -> User: ...
    async def get(self, user_id: UserId) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def delete(self, user_id: UserId) -> None: ...
    async def update(self, user_id: UserId, update_user: UpdateUser) -> User | None: ...
