services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES__URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/{POSTGRES_DB}
      WHISPER__MODEL=${WHISPER_MODEL}
      WHISPER__DEVICE=${WHISPER_DEVICE}
      JWT__SECRET=${JWT_SECRET}
      JWT__ALGORITHM=${JWT_ALGORITHM}
      JWT__EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: