"""initial schema

Revision ID: f583f6d739f8
Revises:
Create Date: 2026-08-06 19:56:32.832091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f583f6d739f8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "speeches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("analysis", postgresql.JSONB(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_speeches_user_id"), "speeches", ["user_id"], unique=False)
    op.create_table(
        "mistake_frequencies",
        sa.Column("speech_id", sa.UUID(), nullable=False),
        sa.Column(
            "category", sa.Enum("ABC", "DEF", name="mistakecategory"), nullable=False
        ),
        sa.Column("opportunities", sa.Integer(), nullable=False),
        sa.Column("occurances", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["speech_id"],
            ["speeches.id"],
        ),
        sa.PrimaryKeyConstraint("speech_id", "category"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mistake_frequencies")
    op.drop_index(op.f("ix_speeches_user_id"), table_name="speeches")
    op.drop_table("speeches")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
