from typing import Protocol

from app.application.use_cases.analytics.models import (
    DistributionResponse,
    TimeBucket,
    Timeframe,
    TimeSeriesResponse,
)
from app.domain.speech import Analysis, MistakeCategory, Speech, SpeechId
from app.domain.user import Email, User, UserId


class UserRepository(Protocol):
    async def create(self, email: Email, password_hash: str) -> User: ...
    async def get(self, user_id: UserId) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def delete(self, user_id: UserId) -> None: ...
    async def update(self, user_id: UserId, password_hash: str) -> User | None: ...


class SpeechRepository(Protocol):
    async def create(self, user_id: UserId, transcript: str, analysis: Analysis) -> Speech: ...
    async def get(self, speech_id: SpeechId) -> Speech | None: ...
    async def delete(self, speech_id: SpeechId) -> None: ...
    async def list(self, user_id: UserId, limit: int, offset: int) -> list[Speech]: ...


class AnalyticsProjector(Protocol):
    async def distribution(
        self, user_id: UserId, timeframe: Timeframe
    ) -> DistributionResponse: ...
    async def time_series(
        self,
        user_id: UserId,
        timeframe: Timeframe,
        mistake_category: MistakeCategory,
        bucket: TimeBucket,
    ) -> TimeSeriesResponse: ...
    async def add_analysis(self, speech_id: SpeechId, analysis: Analysis) -> None: ...
